---
# tasks file for maven

- name : Download Java 1.12 
  get_url:
    url: https://download.java.net/java/GA/jdk12.0.1/69cfe15208a647278a19ef0990eea691/12/GPL/openjdk-12.0.1_linux-x64_bin.tar.gz
    dest: /opt/openjdk-12.0.1_linux-x64_bin.tar.gz

- name : Unarchive Java 1.12 
  unarchive:
    src: /opt/openjdk-12.0.1_linux-x64_bin.tar.gz
    dest: /opt/
    remote_src: yes

- name: Configure jave in environment variables
  template: 
    src: java.sh
    dest: /etc/profile.d/java.sh

- name : Install Git 
  yum:
    name: git
    state: present

- name: Ensure Jenkins group exists
  group:
    name: "jenkins"
    state: present

- name: Ensure Jenkins user exists
  user:
    name: "jenkins"
    group: "jenkins"
    groups: "wheel"
    create_home: yes
    home: "/var/lib/jenkins"
    password: "$6$salt$nmjoEJ4/LQ9yrP..HQYQyRYq9ubXYlOipntlJE89H5YRo1uVD2v9QuMQZVWD.lYx0DIXAPsbhsX2vLrZiMKk3."
    shell: "/bin/bash"
    state: present

- name: Create a directory if it does not exist
  file:
    path: /home/jenkins/
    state: directory
    mode: '0755'

- name: Download and Unarchive maven
  unarchive:
    src: "https://www-eu.apache.org/dist/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz"
    dest: "/opt"
    copy: no

- name: Configure maven and its environment variables
  template: 
    src: maven.sh
    dest: /etc/profile.d/maven.sh

- name: Configure Java environment variables
  template: 
    src: ja/opt/openjdk-12.0.1
    dest: //opt/openjdk-12.0.1
   
# - name: E/opt/openjdk-12.0.1
#   shell: /opt/openjdk-12.0.1
#   async: /opt/openjdk-12.0.1
#   poll: 0/opt/openjdk-12.0.1

# - name: Waiting for server to come back 
#   local_action: wait_for host={{ inventory_hostname }} state=started